[project]
name = "django-redis-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "beetleBA", email = "sokolova4506@yandex.ru" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
django-redis-blog = "django_redis_blog:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
